# Generated by Django 5.0.1 on 2024-01-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allitem',
            old_name='price',
            new_name='product_price',
        ),
        migrations.RenameField(
            model_name='allitem',
            old_name='quantity',
            new_name='product_quantity',
        ),
        migrations.RemoveField(
            model_name='allitem',
            name='id',
        ),
        migrations.AlterField(
            model_name='allitem',
            name='product_id',
            field=models.IntegerField(primary_key=1, serialize=False, unique=1),
        ),
    ]
